#include "settingsPage.h"
#include <QDebug>
#include <array>

settingsPage::settingsPage(std::shared_ptr<GRBL> GRBL_instance, QWidget* parent) : QWidget(parent)
{
    m_pSettingsPageLayout = new QGridLayout();
    this->setLayout(m_pSettingsPageLayout);

    m_pGRBL_instance       = GRBL_instance;

    m_pComPortSelectionBox = new QComboBox();

    m_lPorts               = listPorts();
    m_pComPortSelectionBox->addItems(m_lPorts);

    m_pComPortConnectButton = new QPushButton("Connect");

    m_pSettingsPageLayout->addWidget(m_pComPortSelectionBox, 0, 0);
    m_pSettingsPageLayout->addWidget(m_pComPortConnectButton, 0, 1);

    connect(m_pComPortConnectButton, &QPushButton::clicked, this, &settingsPage::onComPortSetButtonClicked);

    qDebug() << "settingsPage initialized.";
}

settingsPage::~settingsPage()
{
    qDebug() << "settingsPage destroyed.";
}

QList<QString> settingsPage::listPorts()
{
    QList<QString> result;
    std::array<char, 128> buffer;

    // Devcontainer runs Linux, so we only need to scan for standard Linux USB paths
    // plus the /dev/ttyV* path generated by our macOS workaround.
    FILE* pipe = popen("ls /dev/ttyACM* /dev/ttyUSB* /dev/ttyV* 2>/dev/null", "r");

    if (!pipe)
    {
        qDebug("Error: popen() failed!");
    }
    else
    {
        while (fgets(buffer.data(), buffer.size(), pipe) != nullptr)
        {
            result.push_back(((QString) buffer.data()).trimmed());
        }
    }
    if (pipe)
        pclose(pipe);

    return result;
}

int settingsPage::connectPnPMachine(QString comPort, QString csvFile)
{
    return 0;
}

void settingsPage::onComPortSetButtonClicked()
{
    QString comPortSelectionBoxText = m_pComPortSelectionBox->currentText().trimmed();
    QByteArray array                = comPortSelectionBoxText.toLocal8Bit();
    m_sComPort                      = comPortSelectionBoxText.toStdString();

    qDebug() << "Connect Port: |" << m_sComPort.c_str() << "|";

    m_pGRBL_instance->connect(m_sComPort.c_str());

    // if (m_pPnPRunner_instance->getPnPMachine()->getState() == IDLE)
    // {
    //     m_pComPortConnectButton->setStyleSheet("background-color: green;");
    // }
    // else
    // {
    //     m_pComPortConnectButton->setStyleSheet("background-color: red;");
    // }
}
